name: commit-workflow
on: [push]
jobs:
  convert-yaml-to-html:
    runs-on: ubuntu-20.04
    steps:
      #
      # Checkout the content repository:
      #
      - uses: actions/checkout@v2
        with:
          path: 'vibrant-games/content'

      #
      # Checkout the source repository:
      #
      - uses: actions/checkout@v2
        with:
          repository: vibrant-games/source
          # The main branch:
          ref: refs/heads/main
          path: 'vibrant-games/source'
          # Private repos:
          # https://github.com/actions/checkout#Checkout-multiple-repos-private
          # https://github.com/vibrant-games/content/settings/secrets/actions
          token: ${{ secrets.REPO_SOURCE_READONLY }}

      #
      # Install pre-requisite commands and libraries:
      #
      - run: vibrant-games/source/applications/tools/setup.sh

      #
      # Convert all NPCs from YAML to HTML:
      #
      - run: vibrant-games/source/applications/tools/npcs_yaml_to_html.sh vibrant-games/content

      #
      # Commit the NPC HTML files to the content repository:
      #
      - uses: EndBug/add-and-commit@v7
        with:
          cwd: 'vibrant-games/content'
          add:
	  - 'npcs/html'
	  - 'npcs/pdf'
          author_name: GitHub Actions NPCs YAML-to-HTML
          author_email: jtienhaara@yahoo.com
          message: 'GitHub Actions NPCs YAML-to-HTML conversion'
          push: true
